sudo: required
dist: trusty
language: node_js

node_js:
  - '4.4.2'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-7-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono

script:
  - 'cd modules/der-reader'
  - 'npm install'
  - 'npm run build'
  - 'cd ../..'

after_success:
  - ./deploy-to-gh-pages.sh

cache:
  directories:
    - node_modules

deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  file_glob: true
  file:
    - "$TRAVIS_BUILD_DIR/electron/dist/accessimap*"
    - "$TRAVIS_BUILD_DIR/cordova/platforms/android/build/outputs/apk/*.apk"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
