version: 0.4.{build}

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - yarn install
  - yarn add electron-builder@next --dev # force install next version to test electron-builder

build_script:
  - 'cd modules/der-reader'
  - 'npm install'
  - 'npm run build'
  - 'cd ../../electron'
  - 'npm install'
  - 'build --dir'
  - 'ls $TRAVIS_BUILD_DIR/electron/dist/accessimap*'

test: off